[workspace]
# disable the changelog for all packages
changelog_update = false

publish = false

[[package]]
name = "monitor"
# enable the changelog for this package
changelog_update = true
# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"

[[package]]
name = "failing-program"
release = false
changelog_update = false
